* README
** Try it out
Inserts `jay-latex-yosemite-setup.el` into your emacs' init file
*** calling `org-export-dispatch`
**** export to latex
`M-x: org-export-dispatch` `l l`
open the tex generated file

**** export to pdf, A pdf file and open
`M-x: org-export-dispatch` `l o`
**** export to reveal.js
`M-x: org-export-dispatch` `R R`

*** from the command line

#+srcname: compile the latex document
#+begin_src shell 
pdflatex  -file-line-error  --synctex=1 -interaction=nonstopmode "\input" document-example.tex
#+end_src


** Headers explanation
*** #+LaTeX_CLASS
*** #+OPTIONS
An explanation of each defined option can be found in [[http://orgmode.org/manual/Export-settings.html#fnd-2][org-mode-export-settings]]

#+srcname: options example
#+begin_src org
#+OPTIONS: H:1 num:t toc:t :nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:t tags:not-in-toc
#+end_src

**** Useful options
***** H:
Set the number of headline levels for export (org-export-headline-levels). Below
that level, headlines are treated differently. In most back-ends, they become
list items.

***** num:
Toggle section-numbers (org-export-with-section-numbers). It can also be set to
a number ‘n’, so only headlines at that level or above will be numbered.
Finally, irrespective of the level of a specific headline, the numbering of it
can be disabled by setting the UNNUMBERED property to non-nil. This also affects
subheadings.

***** f:
Toggle the inclusion of footnotes (org-export-with-footnotes). 

***** tags:
Toggle inclusion of tags, may also be not-in-toc (org-export-with-tags). 



*** #+EXPORT_EXCLUDE_TAGS
*** #+LATEX_HEADER

** TODOS
*** TODO find out meaning of options
#+OPTIONS:   H:1 num:t toc:t :nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:t tags:not-in-toc
#+EXPORT_EXCLUDE_TAGS: noexport

*** TODO chose opensource licensed fonts
https://fontlibrary.org/
**** search for alternatives to 
  - Garamond Premier Pro
  - Myriad Pro
  - Gill Sans Display MT Pro

**** Available options Options:
http://www.georgduffner.at/ebgaramond/
http://www.1001fonts.com/chunkfive-font.html
https://fontlibrary.org/en/font/gelasio

*** TODO increase spacing between paragraphs
*** TODO increase spacing between numbered list items
*** TODO increase spacing between bulleted list items
*** TODO in the right header (rhead), remove space between @title and : character
